spring:
  datasource:
    name: '测试环境数据库'
    url: jdbc:mysql://test.mysql.apitops.com:4310/tops_finance?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: finance_test
    password: 23txjXmoX9dNQrCGBWranDcHxd8pJP
    type: org.apache.tomcat.jdbc.pool.DataSource #http://wiki.jikexueyuan.com/project/tomcat/tomcat-jdbc-pool.html
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 10 #初始化大小
      min-idle: 5 #最小
      max-active: 10 #最大
      max-idle: 10
      max-wait: 60000 #配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: 'SELECT 1 FROM DUAL'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      init-s-q-l: 'set names utf8mb4;'
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50) #超过50ms执行的慢查询警告输出