oss:
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: nDWJmmw6gmZEAEGa
  accessKeySecret: nvrJFWxmtCEGVa5f6sBkvdZlgTlDAj
  bucketName: top-loan
  keyPrefix: keep/dev/
  expires: 30 #30分钟